### PR TITLE
Performance audit

### PR DESCRIPTION
**Pull request by Cluab**
### Completed Project requirements (1h)
- Inserted the following codes 
  ```sql
  -- This will add 3.594.280 visits considering you have 10 animals, 4 vets, and it will use around ~87.000 timestamps (~4min approx.)
  INSERT INTO visits (animal_id, vet_id, date_of_visit) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hours') visit_timestamp;
  -- This will add 2.500.000 owners with full_name = 'Owner <X>' and email = 'owner_<X>@email.com' (~2min approx.)
  insert into owners (full_name, email) select 'Owner ' || generate_series(1,2500000), 'owner_' || generate_series(1,2500000) || '@mail.com';
  ```
- confirm that the following queries are taking more that one second to complete
  - `SELECT COUNT(*) FROM visits where animal_id = 4;`
  - `SELECT * FROM visits where vet_id = 2;`
  - `SELECT * FROM owners where email = 'owner_18327@mail.com';`
- Use `EXPLAIN ANALYZE` on the previous queries to check what is happening. Take screenshots of them.
- Find a way to improve execution time of the queries.
-  Once you succeed, take a screenshot of the `EXPLAIN ANALYZE` result showing that time actually decreased.
- Any changes you made to your database schema should be added to the schema.sql file and commited in a new pull request.
- If decide to commit any `INSERT INTO` queries - remember to add the to the data.sql file. 
- In the pull request description include screenshots with `EXPLAIN ANALYZE` results (before and after you improve the speed) for each of the 3 problematic queries.

### CODE REVIEW

**Comment by Cluab** [comment]
## Before                                                                         
Pasted image 20230123142714 1
## After
Pasted image 20230123144059

**Comment by Cluab** [comment]
## Before
Pasted image 20230123142508

## After
Screenshot from 2023-01-23 16-40-22

**Comment by Cluab** [comment]
## Before
image

## After
image

**Review by KayLemba — APPROVED** [review]
[# STATUS: APPROVED :green_circle: :clap: 

Hello  @Cluab @belalgamal46        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: aa
Congratulations! 🎉 

HIGHLIGHTS:

- [x]  Your repo is professional 
- [x] Descriptive P.R








 








Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 



well-1

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._]

**Pull request merged**
